eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8072

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
