eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

test:
  prop: lol

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stuffadmin
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update