eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

test:
  prop: lol

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/stuffadmin
    username: postgres
    password: password
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update